import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen">
        <section className="flex h-full items-center justify-center">
          <h1 className=" text-8xl font-bold">Portfolio</h1>
        </section>

        {/* todo: projects, about */}
      </main>

      <footer className=""></footer>
    </>
  );
};

export default Home;
